const BAD_REQUEST = 400;
const UNAUTHORIZED_ACCESS = 401;
const FORBIDEN = 403;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const CONFLICTING_ERROR = 409;

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED_ACCESS,
  NOT_FOUND,
  SERVER_ERROR,
  CONFLICTING_ERROR,
  FORBIDEN,
};
